### ISSUE TITLE
Implement all metadata checks

### ISSUE THREAD

**Issue by jarad** [reichlab/covid19-forecast-hub#574]
The attempt here is to list all metadata checks that should be implemented. Rather than discussing a specific check here, start a new issue for that specific check and link it to this issue.

- [x] must include non-empty `team_name`
- [x] must include non-empty `team_abbr`
- [x] must include non-empty  `model_name`
- [x] must include non-empty  `model_abbr`
- [x] must include non-empty  `model_contributors`
- [x] must include non-empty  `website_url`
- [x] must include non-empty  `license`
- [x] must include non-empty  `team_model_designation`(#349)
- [x] must include non-empty  `methods`

- [x] `team_abbr` is less than 15 characters
- [x] `model_abbr` is less than 15 characters
- [x] `model_contributors` has correct formatting
- [x] `model_contributors` has at least one email
- [x] `website_url` is a valid url
- [x] `license` is one of [these keywords](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository) or "LICENSE.txt" (or cc-by-nc-4.0 for now)
- [x] `team_model_designation` is "primary", "secondary", "proposed", or "other"
- [x] `methods` is less than 200 characters
- [x] `repo_url` is a valid url
- [x] `this_model_is_an_ensemble` is true/false (DEPRECATED)
- [x] `citation` is a valid url

- [x] `team_abbr` is unique (#479)
- [x] `team_abbr`+`model_abbr` is unique (#479)

**Comment by alexrobwong** [comment]
Hi Jarad and Abdul, 

Thank you for starting this thread regarding metadata checks. In an effort to standardize the metadata.txt files, I had noticed that your team had helped updated many (if not all) metadata files for each team, including ours, OliverWyman-Navigator.

It appears that this change is causing the Travis CI check to fail, and as a result, the build to fail. I've taken a look at the build logs and am having trouble understanding why the metadata file is failing. My questions:

 1.) The build failed using the updated Metadata file; do we need to try to make additional changes so that the build is successful? 

2.) If we want to make additional changes, have the local validation checks been updated such that they are reliable to check our changes? 

3.) Should our metadata file be .txt or .yaml format?

**Comment by hannanabdul55** [comment]
Did you pull all the changes from `master`? Also, which PR are you referring to?

**Comment by alexrobwong** [comment]
Hi Abdul,

I am referring to a historical PR that had been approved and merged: [](https://github.com/reichlab/covid19-forecast-hub/tree/master/data-processed/OliverWyman-Navigator)

My concern here is how the build had failed after the metadata file was updated. Please correct me if I am mis-interpreting something here or if there is nothing I should be concerned about. 

My team has not made a PR yet for this week's csv submission. Will be sure to pull all changes from master as we will be attempting to submit shortly. 

Kind regards,
Alex

**Comment by hannanabdul55** [comment]
I think that was because of some other errors. You should most probably be good if you use this metadata file. we fixed all metadata errors for all the models and the subsequent build are passing.

**Comment by alexrobwong** [comment]
Hi Abdul,

Thank you for your guidance. We are happy to use this metadata file for the time being, although do have updates we would like to make. 

Once such changes are made (most likely for next week's submission), should our metadata file be .txt or .yaml format? 

Kind regards,
Alex

@dsiegel125

**Comment by hannanabdul55** [comment]
Oops, sorry I forgot to clarify that. No, you don't have to change the name of your metadata, you can keep it with the `.txt` extension itself.

**Comment by alexrobwong** [comment]
Thank you Abdul! You help is greatly appreciated.

**Comment by alexrobwong** [comment]
Hi Abdul, 

I've ensured to use the updated master however when trying to run the local validation check, the script crashes when trying to read the metadata file. The error message I'm receiving is as follows:

```
 raise CoreError(u"Unable to load source_file. Unknown file format of specified file path: {0}".format(source_file))
pykwalify.errors.CoreError: <CoreError: error code 3: Unable to load source_file. Unknown file format of specified file path: ./data-processed/OliverWyman-Navigator/metadata-OliverWyman-Navigator.txt: Path: '/'>
```

From what I've been able to research so far, its because pykwalify can't read in the text? For context, I'm using the same text file for our team which is on the master branch.

To the extent possible, @dsiegel125 and I would very much like to ensure local validation of our csv before formal PR submission. 

Kind regards,
Alex

**Comment by hannanabdul55** [comment]
Could you uninstall the pykwalify version on your environment and instead run `pip3 install -r validation/requirements.txt` from the root of the github repository. this will install a forked version of pykwalify that we use.

**Comment by jarad** [comment]
Added #689

**Comment by jarad** [comment]
@hannanabdul55 How are these last two checks coming along?

**Comment by alexrobwong** [comment]
Hi Jarad, Abdul,

Apologies for the delay in response. After following Abdul's instructions on uninstalling pykwalify and instead `running pip3 install -r validation/requirements.tx` validation check for last weeks submission (July 28th) worked as expected. 

Will be submitting again for this week shortly. Thank you again very much for your help!

Kind regards,
Alex
